# Generated by Django 3.0.7 on 2020-06-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_cart',
        ),
    ]
